version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - my_network
    ports:
      - "5000:5000"
  
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - my_network
    ports:
      - "8050:8050"

networks:
  my_network:
    driver: bridge
